<?php
/**
 * Created by PhpStorm.
 * User: jx
 * Date: 2016/8/6
 * Time: 9:41
 */
abstract class Component {
    private $name;
    public function getName(){
        return $this->name;
    }
    abstract public function getDescription();
}

abstract class Decorator extends Component{
    private $component;
    public function __construct(Component $component)
    {
        $this->component = $component;
    }
}

class OneComponent extends Component {
    private $name = 'one component';
    public function getName()
    {
        return $this->getName(); // TODO: Change the autogenerated stub
    }
    public function getDescription()
    {
        return 'extends from Component';// TODO: Implement getDescription() method.
    }
}

class OneDecorator extends Decorator {
    private $name = 'one decorator';
    private $component;
    public function __construct(Component $component)
    {
        parent::__construct($component);
    }

    public function getName()
    {
        return 'I am a'.$this->component->getName().' decorator';
    }

    public function getDescription()
    {
        return 'I extends from Decorator, and my componenet extends from'.$this->component->getDescription();// TODO: Implement getDescription() method.
    }
}